Repository lattice/quda, pull requests merged in 2018-09, with the labels that each got.

#724 Update Eigen to 3.3.5
  CMakeLists.txt
Labels: build

#723 Hotfix/qmp rank order
  lib/dslash_policy.cuh
  lib/gauge_plaq.cu
  lib/pgauge_exchange.cu
  tests/invert_test.cpp
  tests/multigrid_benchmark_test.cu
  tests/su3_test.cpp
  tests/test_util.cpp
Labels: bug

#717 HISQ stencils plus general staggered features/cleanup
  include/dirac_quda.h
  lib/CMakeLists.txt
  lib/color_spinor_util.cu
  lib/comm_common.cpp
  lib/cuda_gauge_field.cu
  lib/dirac_improved_staggered.cpp
  lib/dirac_staggered.cpp
  lib/dslash_improved_staggered.cu
  lib/dslash_quda.cuh
  lib/dslash_staggered.cu
  lib/interface_quda.cpp
  lib/llfat_quda.cu
  lib/milc_interface.cpp
  lib/quda_matrix.h
  lib/staggered_dslash_def.h
  lib/unitarize_links_quda.cu
  tests/CMakeLists.txt
  tests/hisq_stencil_test.cpp
  tests/llfat_reference.cpp
  tests/llfat_reference.h
  tests/misc.cpp
  tests/misc.h
  tests/staggered_dslash_ctest.cpp
  tests/staggered_dslash_reference.cpp
  tests/staggered_dslash_reference.h
  tests/staggered_dslash_test.cpp
  tests/staggered_invert_test.cpp
  tests/test_util.cpp
  tests/test_util.h
Labels: feature

#734 Hotfix/jitify options
  CMakeLists.txt
  include/externals/jitify.hpp
  include/jitify_helper.cuh
  include/jitify_options.hpp.in
  jitify.sh
  lib/CMakeLists.txt
Labels: bug
