Repository lattice/quda, pull requests merged in 2018-06, with the labels that each got.

#697 bump required cmake version to 3.8 for multigrid
  CMakeLists.txt
Labels: build

#695 Feature/p2p write optimize
  include/color_spinor_field.h
  include/quda_cuda_api.h
  include/quda_internal.h
  include/tune_quda.h
  lib/CMakeLists.txt
  lib/Makefile
  lib/blas_cublas.cu
  lib/clover_deriv_quda.cu
  lib/clover_invert.cu
  lib/clover_outer_product.cu
  lib/clover_quda.cu
  lib/color_spinor_field.cpp
  lib/contract.cu
  lib/cuda_color_spinor_field.cu
  lib/cuda_gauge_field.cu
  lib/dslash_clover.cu
  lib/dslash_clover_asym.cu
  lib/dslash_domain_wall.cu
  lib/dslash_domain_wall_4d.cu
  lib/dslash_improved_staggered.cu
  lib/dslash_mobius.cu
  lib/dslash_ndeg_twisted_mass.cu
  lib/dslash_pack.cu
  lib/dslash_policy.cuh
  lib/dslash_quda.cuh
  lib/dslash_staggered.cu
  lib/dslash_twisted_clover.cu
  lib/dslash_twisted_mass.cu
  lib/dslash_wilson.cu
  lib/extended_color_spinor_utilities.cu
  lib/field_strength_tensor.cu
  lib/gauge_ape.cu
  lib/gauge_fix_fft.cu
  lib/gauge_fix_ovr.cu
  lib/gauge_force.cu
  lib/gauge_plaq.cu
  lib/gauge_random.cu
  lib/gauge_stout.cu
  lib/interface_quda.cpp
  lib/inv_cg_quda.cpp
  lib/ks_force_quda.cu
  lib/llfat_quda.cu
  lib/momentum.cu
  lib/multi_reduce_core.cuh
  lib/pgauge_det_trace.cu
  lib/pgauge_exchange.cu
  lib/pgauge_heatbath.cu
  lib/pgauge_init.cu
  lib/qcharge_quda.cu
  lib/quda_cuda_api.cpp
  lib/quda_memcpy.cpp
  lib/random.cu
  lib/reduce_core.cuh
  lib/shift_quark_field.cu
  lib/staggered_oprod.cu
  lib/timer.cpp
  lib/transfer.cpp
  lib/unitarize_force_quda.cu
  lib/unitarize_links_quda.cu
  tests/pack_test.cpp
Labels: optimization

#682 Feature/milc optimize
  CMakeLists.txt
  include/fermion_force_quda.h
  include/gauge_field.h
  include/ks_improved_force.h
  include/quda.h
  include/quda_milc_interface.h
  lib/CMakeLists.txt
  lib/Makefile
  lib/blas_quda.cu
  lib/cpu_gauge_field.cpp
  lib/cuda_gauge_field.cu
  lib/dslash_constants.h
  lib/fermion_force_quda.cu
  lib/force_common.h
  lib/gauge_field.cpp
  lib/hisq_force_macros.h
  lib/hisq_paths_force_core.h
  lib/hisq_paths_force_quda.cu
  lib/interface_quda.cpp
  lib/inv_multi_cg_quda.cpp
  lib/llfat_quda.cu
  lib/milc_interface.cpp
  lib/unitarize_force_quda.cu
  make.inc.in
  tests/CMakeLists.txt
  tests/Makefile
  tests/fermion_force_reference.cpp
  tests/fermion_force_reference.h
  tests/fermion_force_test.cpp
  tests/hisq_paths_force_test.cpp
Labels: clean-up, feature, optimization

#706 Saving gauge fields + standalone heatbath
  include/qio_field.h
  include/quda.h
  lib/interface_quda.cpp
  lib/qio_field.cpp
  tests/CMakeLists.txt
  tests/gauge_alg_test.cpp
  tests/heatbath_test.cpp
  tests/test_util.cpp
Labels: feature
