Repository lattice/quda, pull requests merged in 2018-07, with the labels that each got.

#705 Enable ctest functionality to allow automated run time tests
  CMakeLists.txt
  include/comm_quda.h
  include/quda.h
  lib/comm_common.cpp
  lib/dslash_core/tm_ndeg_dslash_core.h
  lib/dslash_core/tm_ndeg_dslash_dagger_core.h
  lib/dslash_core/tm_ndeg_fused_exterior_dslash_core.h
  lib/dslash_core/tm_ndeg_fused_exterior_dslash_dagger_core.h
  lib/dslash_pack.cu
  lib/generate/fused_exterior_ndeg_tm_dslash_cuda_gen.py
  lib/generate/ndeg_tm_dslash_cuda_gen.py
  lib/interface_quda.cpp
  tests/CMakeLists.txt
  tests/blas_test.cu
  tests/dslash_ctest.cpp
  tests/gtest-all.cc
  tests/gtest.h
  tests/staggered_dslash_ctest.cpp
Labels: build, feature

#708 Feature/trace
  include/malloc_quda.h
  lib/dslash_coarse.cu
  lib/dslash_pack.cu
  lib/dslash_quda.cuh
  lib/malloc.cpp
  lib/multi_reduce_core.cuh
  lib/tune.cpp
  tests/CMakeLists.txt
  tests/blas_test.cu
Labels: bug, feature

#710 Enable testing of GDR policies
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#711 Hisq stencil unit test
  lib/interface_quda.cpp
  tests/CMakeLists.txt
  tests/hisq_stencil_test.cpp
  tests/test_util.cpp
Labels: feature

#713 Fixed bugs in staggered_dslash_ctest
  tests/staggered_dslash_ctest.cpp
Labels: bug
