Repository lattice/quda, pull requests merged in 2018-08, with the labels that each got.

#719 Use refinement_sloppy precision for multi shift refinement
  include/invert_quda.h
  include/quda.h
  lib/check_params.h
  lib/interface_quda.cpp
  lib/inv_cg_quda.cpp
  lib/inv_multi_cg_quda.cpp
  lib/quda_fortran.F90
  tests/invert_test.cpp
  tests/staggered_invert_test.cpp
  tests/test_util.cpp
Labels: optimization

#720 Hotfix/profile naik epsilon
  include/quda_constants.h
  include/quda_milc_interface.h
  lib/milc_interface.cpp
  lib/tune.cpp
Labels: bug

#722 Hotfix/gcc 5.5
  include/quda_arpack_interface.h
  lib/blas_magma.cu
  lib/blas_magma_nopiv.cu
  lib/copy_color_spinor.cuh
  lib/copy_color_spinor_mg.cuh
  lib/interface_quda.cpp
  lib/quda_arpack_interface.cpp
  lib/quda_fortran.F90
  lib/reduce_quda.cu
  lib/spinor_gauss.cu
  tests/gtest.h
  tests/multigrid_benchmark_test.cu
Labels: bug, build
