Repository lattice/quda, pull requests merged in 2019-05, with the labels that each got.

#803 jitified the qcharge routine, removed spurious location param from ga…
  include/gauge_tools.h
  include/kernels/gauge_qcharge.cuh
  include/quda.h
  lib/CMakeLists.txt
  lib/field_strength_tensor.cu
  lib/gauge_field_strength_tensor.cu
  lib/gauge_plaq.cu
  lib/gauge_qcharge.cu
  lib/interface_quda.cpp
  lib/pgauge_exchange.cu
  lib/pgauge_heatbath.cu
  lib/pgauge_init.cu
  lib/qcharge_quda.cu
  tests/gauge_alg_test.cpp
  tests/heatbath_test.cpp
  tests/multigrid_evolve_test.cpp
  tests/su3_test.cpp
Labels: clean-up, feature

#799 Hotfix/milc bnl
  CMakeLists.txt
  include/comm_quda.h
  include/dslash.h
  include/dslash_helper.cuh
  include/kernels/dslash_pack.cuh
  include/mpi_comm_handle.h
  include/multigrid.h
  include/texture.h
  include/transfer.h
  include/util_quda.h
  lib/blas_quda.cu
  lib/clover_outer_product.cu
  lib/clover_sigma_outer_product.cu
  lib/color_spinor_field.cpp
  lib/color_spinor_util.cu
  lib/comm_common.cpp
  lib/comm_mpi.cpp
  lib/comm_qmp.cpp
  lib/comm_single.cpp
  lib/copy_color_spinor.cuh
  lib/copy_quda.cu
  lib/covDev.cu
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/dslash_coarse.cu
  lib/dslash_policy.cuh
  lib/gauge_field.cpp
  lib/interface_quda.cpp
  lib/lattice_field.cpp
  lib/layout_hyper.c
  lib/malloc.cpp
  lib/milc_interface.cpp
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/multigrid.cpp
  lib/qio_field.cpp
  lib/random.cu
  lib/reduce_quda.cu
  lib/spinor_noise.cu
  lib/staggered_oprod.cu
  lib/transfer.cpp
  lib/util_quda.cpp
  tests/covdev_test.cpp
  tests/invert_test.cpp
  tests/multigrid_invert_test.cpp
  tests/staggered_dslash_test.cpp
  tests/test_util.cpp
  tests/test_util.h
Labels: bug, feature

#808 Hotfix/milc naive
  include/kernels/gauge_qcharge.cuh
  lib/check_params.h
  lib/gauge_qcharge.cu
  lib/interface_quda.cpp
  lib/milc_interface.cpp
Labels: bug, clean-up

#810 bump Eigen to 3.3.7
  CMakeLists.txt
Labels: build

#809 Use NVTX3 if available
  CMakeLists.txt
  include/timer.h
  lib/generate/nvtx.w
  lib/milc_interface.cpp
  lib/nvtx_pmpi.c
  lib/transfer.cpp
Labels: build, clean-up

#817 Block ortho optimization
  include/kernels/block_orthogonalize.cuh
  lib/block_orthogonalize.cu
Labels: optimization

#818 Placed error on dir in the proper place
  include/kernels/laplace.cuh
Labels: bug

#819 Add ability to download and build QIO and QMP to cmake
  CMakeLists.txt
  lib/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#824 fix dependency on QMP/QIO for tests
  .cmake-format.py
  CMakeLists.txt
  lib/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#822 Feature/multi blas fast compile
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  tests/blas_test.cu
Labels: optimization
