Repository lattice/quda, pull requests merged in 2019-02, with the labels that each got.

#766 Feature/ca-cg
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/invert_quda.h
  include/quda.h
  lib/check_params.h
  lib/inv_ca_cg.cpp
  lib/inv_ca_gcr.cpp
  lib/inv_cg_quda.cpp
  lib/inv_gcr_quda.cpp
  lib/multigrid.cpp
  lib/solver.cpp
  tests/invert_test.cpp
  tests/misc.cpp
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/staggered_invert_test.cpp
  tests/test_util.cpp
Labels: feature

#763 Hotfix/cmake power
  CMakeLists.txt
Labels: build

#773 Fixed initialization bug for CA-CG with Chebyshev basis.
  lib/inv_ca_cg.cpp
Labels: bug

#775 Feature/rewrite staggered
  .gitignore
  include/color_spinor.h
  include/dslash_helper.cuh
  include/dslash_quda.h
  include/gauge_field_order.h
  include/index_helper.cuh
  include/kernels/dslash_staggered.cuh
  lib/CMakeLists.txt
  lib/copy_gauge_inc.cu
  lib/cuda_color_spinor_field.cpp
  lib/dirac_improved_staggered.cpp
  lib/dirac_staggered.cpp
  lib/dslash_improved_staggered.cu
  lib/dslash_pack.cu
  lib/dslash_pack2.cu
  lib/dslash_staggered.cu
  lib/extract_gauge_ghost.cu
  lib/gauge_field.cpp
  lib/staggered_dslash.cu
  tests/staggered_dslash_ctest.cpp
  tests/staggered_dslash_test.cpp
  tests/test_util.cpp
Labels: clean-up, optimization
