Repository lattice/quda, pull requests merged in 2019-09, with the labels that each got.

#888 Hotfix/invertmsrc
  include/kernels/dslash_domain_wall_4d.cuh
  include/kernels/dslash_domain_wall_m5.cuh
  include/mpi_comm_handle.h
  include/texture.h
  lib/dslash_domain_wall_4d.cu
  lib/staggered_oprod.cu
  tests/invertmsrc_test.cpp
Labels: bug

#889 Fix ASAN warnings in invert_test and multigrid_invert_test
  tests/invert_test.cpp
  tests/multigrid_invert_test.cpp
Labels: bug

#893 made load_norm const to fix compilation
  include/texture.h
Labels: bug

#896 Hotfix/develop cherry picking
  include/color_spinor_field.h
  include/eigensolve_quda.h
  include/malloc_quda.h
  lib/blas_cublas.cu
  lib/multigrid.cpp
Labels: bug

#894 Hotfix/blas svd deflate
  include/color_spinor_field.h
  include/eigensolve_quda.h
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/malloc_quda.h
  include/multi_blas_helper.cuh
  include/texture.h
  lib/blas_cublas.cu
  lib/blas_quda.cu
  lib/eigensolve_quda.cpp
  lib/inv_cg_quda.cpp
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/multigrid.cpp
  lib/reduce_quda.cu
  tests/blas_test.cu
Labels: bug

#901 Feature/alias sloppy
  include/color_spinor_field.h
  include/invert_quda.h
  lib/color_spinor_field.cpp
  lib/inv_ca_gcr.cpp
  lib/inv_gcr_quda.cpp
Labels: feature, optimization

#899 Feature/pack fuse
  CMakeLists.txt
  include/dslash.h
  include/dslash_helper.cuh
  include/jitify_helper.cuh
  include/kernels/covDev.cuh
  include/kernels/dslash_domain_wall_4d.cuh
  include/kernels/dslash_domain_wall_5d.cuh
  include/kernels/dslash_ndeg_twisted_mass.cuh
  include/kernels/dslash_ndeg_twisted_mass_preconditioned.cuh
  include/kernels/dslash_pack.cuh
  include/kernels/dslash_staggered.cuh
  include/kernels/dslash_twisted_clover_preconditioned.cuh
  include/kernels/dslash_twisted_mass.cuh
  include/kernels/dslash_twisted_mass_preconditioned.cuh
  include/kernels/dslash_wilson.cuh
  include/kernels/dslash_wilson_clover.cuh
  include/kernels/dslash_wilson_clover_preconditioned.cuh
  include/kernels/laplace.cuh
  include/lattice_field.h
  include/multi_blas_helper.cuh
  include/quda_internal.h
  lib/covDev.cu
  lib/dslash_domain_wall_4d.cu
  lib/dslash_domain_wall_5d.cu
  lib/dslash_improved_staggered.cu
  lib/dslash_ndeg_twisted_mass.cu
  lib/dslash_ndeg_twisted_mass_preconditioned.cu
  lib/dslash_policy.cuh
  lib/dslash_staggered.cu
  lib/dslash_twisted_clover.cu
  lib/dslash_twisted_clover_preconditioned.cu
  lib/dslash_twisted_mass.cu
  lib/dslash_twisted_mass_preconditioned.cu
  lib/dslash_wilson.cu
  lib/dslash_wilson_clover.cu
  lib/dslash_wilson_clover_preconditioned.cu
  lib/laplace.cu
  tests/CMakeLists.txt
Labels: bug, clean-up, feature

#905 Hotfix/misc
  include/dslash.h
  lib/inv_gmresdr_quda.cpp
  lib/multi_reduce_quda.cu
  lib/reduce_quda.cu
  lib/transfer.cpp
  tests/CMakeLists.txt
Labels: bug, clean-up

#906 Feature/thinning
  include/color_spinor_field.h
  include/dslash_quda.h
  include/kernels/dslash_pack.cuh
  include/kernels/laplace.cuh
  lib/CMakeLists.txt
  lib/color_spinor_wuppertal.cu
  lib/copy_color_spinor_dh.cu
  lib/copy_color_spinor_dq.cu
  lib/copy_color_spinor_ds.cu
  lib/copy_color_spinor_hd.cu
  lib/copy_color_spinor_hh.cu
  lib/copy_color_spinor_hq.cu
  lib/copy_color_spinor_hs.cu
  lib/copy_color_spinor_qd.cu
  lib/copy_color_spinor_qh.cu
  lib/copy_color_spinor_qq.cu
  lib/copy_color_spinor_qs.cu
  lib/copy_color_spinor_sh.cu
  lib/copy_color_spinor_sq.cu
  lib/copy_color_spinor_ss.cu
  lib/dslash_pack2.cu
  lib/extract_gauge_ghost.cu
  lib/extract_gauge_ghost_extended.cu
  lib/extract_gauge_ghost_mg.cu
  lib/gauge_laplace.cpp
  lib/interface_quda.cpp
  lib/laplace.cu
  lib/max_clover.cu
  lib/max_gauge.cu
  lib/spinor_noise.cu
  tests/blas_test.cu
Labels: clean-up

#858 Use CLI11 for option parsing
  CMakeLists.txt
  LICENSE
  include/externals/CLI11.hpp
  lib/unitarize_links_quda.cu
  tests/CMakeLists.txt
  tests/blas_test.cu
  tests/contract_test.cpp
  tests/covdev_test.cpp
  tests/deflated_invert_test.cpp
  tests/dslash_ctest.cpp
  tests/dslash_test.cpp
  tests/eigensolve_test.cpp
  tests/gauge_alg_test.cpp
  tests/gauge_force_test.cpp
  tests/heatbath_test.cpp
  tests/hisq_paths_force_test.cpp
  tests/hisq_stencil_test.cpp
  tests/hisq_unitarize_force_test.cpp
  tests/invert_test.cpp
  tests/invertmsrc_test.cpp
  tests/llfat_test.cpp
  tests/misc.cpp
  tests/misc.h
  tests/multigrid_benchmark_test.cu
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/pack_test.cpp
  tests/plaq_test.cpp
  tests/staggered_dslash_ctest.cpp
  tests/staggered_dslash_test.cpp
  tests/staggered_eigensolve_test.cpp
  tests/staggered_invert_test.cpp
  tests/staggered_invertmsrc_test.cpp
  tests/su3_test.cpp
  tests/test_params.cpp
  tests/test_params.h
  tests/test_util.cpp
  tests/test_util.h
  tests/unitarize_link_test.cpp
Labels: clean-up, feature

#909 Further thinning and fixes
  CMakeLists.txt
  include/blas_quda.h
  include/color_spinor_field.h
  include/dirac_quda.h
  include/dslash.h
  include/gauge_field_order.h
  include/index_helper.cuh
  include/kernels/dslash_staggered.cuh
  include/kernels/gauge_plaq.cuh
  include/kernels/gauge_qcharge.cuh
  include/launch_kernel.cuh
  include/quda_internal.h
  lib/CMakeLists.txt
  lib/blas_quda.cu
  lib/block_orthogonalize.cu
  lib/clover_invert.cu
  lib/color_spinor_pack.cu
  lib/color_spinor_util.cu
  lib/copy_color_spinor.cuh
  lib/copy_color_spinor_mg.cuh
  lib/copy_quda.cu
  lib/cuda_color_spinor_field.cpp
  lib/dirac_clover.cpp
  lib/dirac_clover_hasenbusch_twist.cpp
  lib/dirac_twisted_clover.cpp
  lib/dslash_coarse.cu
  lib/dslash_constants.h
  lib/dslash_quda.cuh
  lib/extended_color_spinor_utilities.cu
  lib/extract_gauge_ghost.cu
  lib/extract_gauge_ghost_extended.cu
  lib/gauge_fix_fft.cu
  lib/gauge_fix_ovr.cu
  lib/gauge_plaq.cu
  lib/gauge_qcharge.cu
  lib/gauge_random.cu
  lib/generic_blas.cuh
  lib/generic_reduce.cuh
  lib/inv_ca_cg.cpp
  lib/inv_gmresdr_quda.cpp
  lib/laplace.cu
  lib/momentum.cu
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/pgauge_det_trace.cu
  lib/prolongator.cu
  lib/reduce_quda.cu
  lib/restrictor.cu
  lib/spinor_noise.cu
  lib/transfer.cpp
  tests/CMakeLists.txt
  tests/gauge_alg_test.cpp
  tests/misc.cpp
  tests/staggered_dslash_test.cpp
  tests/test_util.cpp
  tests/test_util.h
Labels: bug, build, clean-up
