Repository lattice/quda, pull requests merged in 2019-10, with the labels that each got.

#911 avoid QMP/QIO configure in every make invocation
  CMakeLists.txt
  lib/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#918 fix for cublas not always being properly linked
  CMakeLists.txt
  lib/CMakeLists.txt
Labels: build

#917 Stacktrace for not freed mem allocation
  lib/CMakeLists.txt
  lib/malloc.cpp
Labels: feature

#912 Use an enum for test_type in dslash_test
  include/quda.h
  lib/interface_quda.cpp
  tests/CMakeLists.txt
  tests/dslash_ctest.cpp
  tests/dslash_test.cpp
  tests/dslash_test_helpers.cpp
  tests/dslash_test_helpers.h
  tests/staggered_dslash_ctest.cpp
  tests/staggered_dslash_test.cpp
  tests/test_params.h
Labels: clean-up

#922 Bi-directional coarse link build check
  include/dirac_quda.h
  include/multigrid.h
  lib/coarse_op.cu
  lib/coarse_op.cuh
  lib/coarsecoarse_op.cu
  lib/dirac_coarse.cpp
  lib/multigrid.cpp
Labels: bug

#920 Feature/instantiate
  include/dslash.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/gauge_field.h
  include/gauge_field_order.h
  include/instantiate.h
  include/kernels/field_strength_tensor.cuh
  include/kernels/gauge_ape.cuh
  include/kernels/gauge_stout.cuh
  include/ks_improved_force.h
  include/llfat_quda.h
  include/unitarization_links.h
  include/util_quda.h
  lib/CMakeLists.txt
  lib/comm_common.cpp
  lib/gauge_ape.cu
  lib/gauge_field.cpp
  lib/gauge_field_strength_tensor.cu
  lib/gauge_force.cu
  lib/gauge_phase.cu
  lib/gauge_plaq.cu
  lib/gauge_qcharge.cu
  lib/gauge_random.cu
  lib/gauge_stout.cu
  lib/gauge_update_quda.cu
  lib/hisq_paths_force_quda.cu
  lib/instantiate.cpp
  lib/interface_quda.cpp
  lib/llfat_quda.cu
  lib/momentum.cu
  lib/svd_quda.h
  lib/unitarize_force_quda.cu
  lib/unitarize_links_quda.cu
  tests/CMakeLists.txt
  tests/hisq_stencil_test.cpp
  tests/hisq_unitarize_force_test.cpp
  tests/staggered_gauge_utils.cpp
  tests/test_params.cpp
Labels: clean-up, feature

#900 Feature/persistent deflation space
  include/eigensolve_quda.h
  include/invert_quda.h
  include/multigrid.h
  include/quda.h
  lib/check_params.h
  lib/eigensolve_quda.cpp
  lib/interface_quda.cpp
  lib/inv_ca_cg.cpp
  lib/inv_ca_gcr.cpp
  lib/inv_cg_quda.cpp
  lib/inv_eigcg_quda.cpp
  lib/inv_gcr_quda.cpp
  lib/inv_mre.cpp
  lib/multigrid.cpp
  lib/pgauge_heatbath.cu
  lib/solver.cpp
  tests/CMakeLists.txt
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/test_params.cpp
  tests/test_params.h
Labels: feature, optimization
