Repository lattice/quda, pull requests merged in 2019-04, with the labels that each got.

#770 Add support for a user-defined MPI communicator in place of MPI_COMM_…
  include/mpi_comm_handle.h
  include/quda.h
  include/quda_milc_interface.h
  lib/comm_mpi.cpp
  lib/comm_qmp.cpp
  lib/generate/nvtx.w
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/nvtx_pmpi.c
  lib/quda_arpack_interface.cpp
  tests/test_util.cpp
Labels: feature

#794 Hotfix/milc plegma
  .clang-format
  .gitignore
  CMakeLists.txt
  include/gauge_field_order.h
  include/jitify_helper.cuh
  include/kernels/block_orthogonalize.cuh
  include/kernels/coarse_op_kernel.cuh
  include/mpi_comm_handle.h
  include/quda.h
  include/quda_define.h.in
  lib/block_orthogonalize.cu
  lib/coarse_op.cuh
  lib/color_spinor_pack.cu
  lib/comm_mpi.cpp
  lib/comm_qmp.cpp
  lib/dirac_twisted_clover.cpp
  lib/dirac_twisted_mass.cpp
  lib/dslash_coarse.cu
  lib/dslash_quda.cu
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/prolongator.cu
  lib/restrictor.cu
Labels: bug

#789 Feature/cov dev ops rerwite
  CMakeLists.txt
  include/color_spinor_field.h
  include/covDev.h
  include/dirac_quda.h
  include/dslash_helper.cuh
  include/dslash_quda.h
  include/kernels/covDev.cuh
  include/kernels/dslash_pack.cuh
  include/kernels/dslash_staggered.cuh
  include/kernels/dslash_wilson.cuh
  include/kernels/laplace.cuh
  include/quda.h
  include/stencil.h
  lib/check_params.h
  lib/covDev.cu
  lib/cuda_color_spinor_field.cpp
  lib/dirac.cpp
  lib/dslash_constants.h
  lib/dslash_pack2.cu
  lib/dslash_policy.cuh
  lib/gauge_covdev.cpp
  lib/gauge_laplace.cpp
  lib/interface_quda.cpp
  lib/laplace.cu
  lib/quda_fortran.F90
  tests/covdev_reference.cpp
  tests/covdev_test.cpp
  tests/dslash_test.cpp
  tests/staggered_dslash_test.cpp
  tests/staggered_invert_test.cpp
  tests/test_util.cpp
Labels: clean-up, optimization
