Repository lattice/quda, pull requests merged in 2019-06, with the labels that each got.

#816 Feature/deflated mg
  CMakeLists.txt
  include/blas_quda.h
  include/dirac_quda.h
  include/eig_variables.h
  include/eigensolve_quda.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/invert_quda.h
  include/kernels/blas_core.cuh
  include/kernels/block_orthogonalize.cuh
  include/kernels/gauge_qcharge.cuh
  include/kernels/laplace.cuh
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/lanczos_quda.h
  include/multigrid.h
  include/quda.h
  include/quda_arpack_interface.h
  include/ritz_quda.h
  include/timer.h
  lib/CMakeLists.txt
  lib/blas_quda.cu
  lib/block_orthogonalize.cu
  lib/check_params.h
  lib/copy_color_spinor_mg.cuh
  lib/cuda_color_spinor_field.cpp
  lib/deflation.cpp
  lib/eig_lanczos_quda.cpp
  lib/eig_solver.cpp
  lib/eigensolve_quda.cpp
  lib/gauge_qcharge.cu
  lib/interface_quda.cpp
  lib/inv_cg_quda.cpp
  lib/laplace.cu
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/multigrid.cpp
  lib/quda_arpack_interface.cpp
  lib/ritz_quda.cpp
  lib/solver.cpp
  lib/spinor_noise.cu
  lib/timer.cpp
  tests/CMakeLists.txt
  tests/deflated_invert_test.cpp
  tests/dslash_test.cpp
  tests/eigensolve_test.cpp
  tests/invert_test.cpp
  tests/invertmsrc_test.cpp
  tests/misc.cpp
  tests/misc.h
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/staggered_invert_test.cpp
  tests/su3_test.cpp
  tests/test_util.cpp
Labels: feature

#828 Fixed path in lib/CMakeLists to install quda_define.h
  lib/CMakeLists.txt
Labels: build

#827 Feature/low prec lanczos
  include/eigensolve_quda.h
  lib/eigensolve_quda.cpp
  lib/multi_reduce_quda.cu
  lib/quda_arpack_interface.cpp
  lib/spinor_noise.cu
  tests/eigensolve_test.cpp
Labels: bug, clean-up, feature

#829 Hotfix/cmake jitify
  CMakeLists.txt
  include/jitify_options.hpp.in
  lib/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#826 clean up MPI Fortran compiler detection
  CMakeLists.txt
Labels: build

#833 Repeated block orthonormalization
  include/kernels/block_orthogonalize.cuh
  include/multigrid.h
  include/quda.h
  include/transfer.h
  lib/block_orthogonalize.cu
  lib/check_params.h
  lib/multigrid.cpp
  lib/transfer.cpp
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/test_util.cpp
Labels: feature

#820 Download arpack-ng
  CMakeLists.txt
  include/quda_arpack_interface.h
  lib/CMakeLists.txt
  lib/quda_arpack_interface.cpp
  tests/CMakeLists.txt
Labels: build

#837 Pre-compute Yhat max for fixed-precision coarse preconditioned operator
  include/atomic.cuh
  include/kernels/coarse_op_preconditioned.cuh
  lib/coarse_op.cuh
  lib/coarse_op_preconditioned.cu
Labels: feature

#840 remove spurious include directories
  CMakeLists.txt
Labels: clean-up

#842 Fixed bug: initialized max in yhat calculation to zero.
  lib/coarse_op_preconditioned.cu
Labels: bug

#844 Fix atomicMax for floats
  include/atomic.cuh
Labels: bug

#843 Feature/plaq test
  include/color_spinor_field.h
  include/gauge_field.h
  include/gauge_field_order.h
  include/gauge_tools.h
  include/lattice_field.h
  include/quda.h
  include/quda_matrix.h
  include/random_quda.h
  lib/dslash4_staggered.cu
  lib/eigensolve_quda.cpp
  lib/gauge_random.cu
  lib/gauge_update_quda.cu
  lib/interface_quda.cpp
  lib/multigrid.cpp
  lib/pgauge_init.cu
  lib/random.cu
  lib/spinor_noise.cu
  tests/CMakeLists.txt
  tests/gauge_alg_test.cpp
  tests/heatbath_test.cpp
  tests/invert_test.cpp
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/plaq_test.cpp
  tests/test_util.cpp
Labels: bug, feature

#849 Feature/mg per level io
  include/quda.h
  lib/check_params.h
  lib/multigrid.cpp
  tests/deflated_invert_test.cpp
  tests/multigrid_evolve_test.cpp
  tests/multigrid_invert_test.cpp
  tests/test_util.cpp
Labels: bug, feature

#851 Fix QIO/QMP dependency in tests/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#853 Change heavy-quark restart behavior
  include/invert_quda.h
  lib/inv_cg_quda.cpp
  lib/milc_interface.cpp
Labels: bug, optimization
