Repository lattice/quda, pull requests merged in 2019-08, with the labels that each got.

#862 Feature/large multi blas
  CMakeLists.txt
  include/externals/jitify.hpp
  include/jitify_helper.cuh
  include/kernels/dslash_coarse.cuh
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/launch_kernel.cuh
  include/multi_blas_helper.cuh
  include/quda_constants.h
  include/texture.h
  include/tune_quda.h
  lib/blas_quda.cu
  lib/cuda_color_spinor_field.cpp
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/reduce_quda.cu
  lib/tune.cpp
  tests/blas_test.cu
  tests/test_util.cpp
Labels: bug, optimization

#869 Updated reconstruct for fat/long build: originally grabbed the value …
  tests/staggered_gauge_utils.cpp
Labels: clean-up

#876 Fix to zero mass Dirac(Improved)StaggeredPC sign quirk
  lib/dirac_improved_staggered.cpp
  lib/dirac_staggered.cpp
Labels: bug

#884 Hotfix/mg evolve quart blas
  lib/blas_quda.cu
  lib/contract.cu
  lib/multi_blas_quda.cu
  lib/reduce_quda.cu
  tests/multigrid_evolve_test.cpp
Labels: bug
