Repository lattice/quda, pull requests merged in 2020-06, with the labels that each got.

#1007 Feature/oprod
  include/color_spinor.h
  include/index_helper.cuh
  include/kernels/clover_sigma_outer_product.cuh
  include/quda_matrix.h
  lib/clover_outer_product.cu
  lib/clover_sigma_outer_product.cu
  lib/cpu_gauge_field.cpp
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/staggered_oprod.cu
  lib/svd_quda.h
  lib/unitarize_force_quda.cu
  lib/unitarize_links_quda.cu
Labels: bug, clean-up, optimization

#1012 Potential fix for MPI CXX link issue
  lib/CMakeLists.txt
Labels: build

#1013 Support using managed memory for MILC allocations
  include/quda_milc_interface.h
  include/timer.h
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/milc_interface.cpp
  lib/quda_cuda_api.cpp
  lib/timer.cpp
Labels: optimization

#1024 Feature/access rank
  lib/comm_common.cpp
Labels: optimization

#1021 Feature/no tex
  CMakeLists.txt
  include/blas_helper.cuh
  include/blas_quda.h
  include/clover_field.h
  include/clover_field_order.h
  include/color_spinor_field.h
  include/color_spinor_field_order.h
  include/convert.h
  include/cub_helper.cuh
  include/float_vector.h
  include/gauge_field.h
  include/gauge_field_order.h
  include/instantiate.h
  include/kernels/blas_core.cuh
  include/kernels/block_orthogonalize.cuh
  include/kernels/clover_invert.cuh
  include/kernels/gauge_plaq.cuh
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/kernels/reduce_core.cuh
  include/lattice_field.h
  include/multi_blas_helper.cuh
  include/quda_cuda_api.h
  include/quda_matrix.h
  include/register_traits.h
  include/texture.h
  include/texture_helper.cuh
  include/transform_reduce.h
  lib/blas_quda.cu
  lib/block_orthogonalize.cu
  lib/clover_field.cpp
  lib/clover_invert.cu
  lib/clover_quda.cu
  lib/coarse_op.cu
  lib/color_spinor_field.cpp
  lib/color_spinor_util.cu
  lib/copy_color_spinor.cuh
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/deflation.cpp
  lib/dslash5_domain_wall.cu
  lib/dslash5_mobius_eofa.cu
  lib/eigensolve_quda.cpp
  lib/gauge_field.cpp
  lib/generic_blas.cuh
  lib/generic_reduce.cuh
  lib/interface_quda.cpp
  lib/inv_bicgstabl_quda.cpp
  lib/inv_pcg_quda.cpp
  lib/mdw_fused_dslash.cu
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/reduce_quda.cu
  lib/restrictor.cu
  lib/staggered_coarse_op.cu
  lib/svd_quda.h
  tests/CMakeLists.txt
  tests/blas_test.cpp
  tests/dslash_ctest.cpp
  tests/dslash_test.cpp
Labels: clean-up, optimization
