Repository lattice/quda, pull requests merged in 2020-02, with the labels that each got.

#961 Explicit UVM prefetch API
  include/clover_field.h
  include/color_spinor_field.h
  include/dirac_quda.h
  include/gauge_field.h
  include/lattice_field.h
  include/malloc_quda.h
  include/multigrid.h
  lib/clover_field.cpp
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/dirac.cpp
  lib/dirac_clover.cpp
  lib/dirac_coarse.cpp
  lib/dirac_improved_staggered.cpp
  lib/dirac_twisted_clover.cpp
  lib/interface_quda.cpp
  lib/malloc.cpp
  lib/multigrid.cpp
  lib/staggered_prolong_restrict.cu
  lib/transfer.cpp
Labels: feature, optimization

#964 Fix refresh of preconditioned long and fat links
  lib/interface_quda.cpp
Labels: bug

#965 Bump QMP to 2.5.2
  CMakeLists.txt
Labels: build
