Repository lattice/quda, pull requests merged in 2020-01, with the labels that each got.

#946 Intermediately saving the tunecache during an MG setup
  include/blas_cublas.h
  lib/blas_cublas.cu
  lib/blas_magma_nopiv.cu
  lib/dirac_coarse.cpp
  tests/invert_test.cpp
  tests/multigrid_invert_test.cpp
  tests/staggered_invert_test.cpp
  tests/staggered_multigrid_invert_test.cpp
Labels: bug, feature

#948 Feature/mg misc
  include/atomic.cuh
  include/clover_field.h
  include/cub_helper.cuh
  include/gauge_field.h
  include/kernels/coarse_op_kernel.cuh
  include/kernels/coarse_op_preconditioned.cuh
  include/kernels/dslash_staggered.cuh
  include/kernels/dslash_twisted_mass_preconditioned.cuh
  include/kernels/dslash_wilson.cuh
  include/multigrid.h
  include/tune_key.h
  lib/blas_cublas.cu
  lib/block_orthogonalize.cu
  lib/coarse_op.cu
  lib/coarse_op.cuh
  lib/coarse_op_preconditioned.cu
  lib/coarsecoarse_op.cu
  lib/color_spinor_pack.cu
  lib/copy_color_spinor_mg.cuh
  lib/copy_color_spinor_mg_hh.cu
  lib/copy_color_spinor_mg_hq.cu
  lib/copy_color_spinor_mg_hs.cu
  lib/copy_color_spinor_mg_qh.cu
  lib/copy_color_spinor_mg_qq.cu
  lib/copy_color_spinor_mg_qs.cu
  lib/copy_gauge_mg.cu
  lib/cuda_color_spinor_field.cpp
  lib/dslash_improved_staggered.cu
  lib/dslash_staggered.cu
  lib/extract_gauge_ghost_mg.cu
  lib/generic_blas.cuh
  lib/generic_reduce.cuh
  lib/laplace.cu
  lib/max_clover.cu
  lib/max_gauge.cu
  lib/multigrid.cpp
  lib/restrictor.cu
  lib/staggered_coarse_op.cu
  lib/transfer.cpp
Labels: build, optimization

#950 Hotfix/partition
  CMakeLists.txt
  lib/comm_common.cpp
Labels: bug

#953 Updates to Doxygen for 1.0
  doc/Doxyfile.in
Labels: documentation

#952 Hotfix/gauge memset
  lib/cpu_gauge_field.cpp
Labels: bug

#954 Hotfix/cpu mg setup
  include/color_spinor_field_order.h
  include/kernels/block_orthogonalize.cuh
  lib/coarsecoarse_op.cu
  lib/cuda_gauge_field.cpp
  lib/interface_quda.cpp
  lib/transfer.cpp
Labels: bug, build

#958 improve linking against cufft and curand
  CMakeLists.txt
  lib/CMakeLists.txt
Labels: build
