Repository lattice/quda, pull requests merged in 2020-07, with the labels that each got.

#1028 Hotfix/multiblas
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/multi_blas_helper.cuh
  lib/blas_quda.cu
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/reduce_quda.cu
  tests/blas_test.cpp
Labels: bug, clean-up

#1018 Handle MILC staggerd phase removal in QUDA
  include/quda_milc_interface.h
  lib/gauge_phase.cu
  lib/interface_quda.cpp
  lib/milc_interface.cpp
Labels: optimization

#1033 Fix bug in NXZ template instantiation in multi-blas and multi-reduce
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
Labels: bug

#1002 MILC interface for HISQ MG
  README.md
  include/dirac_quda.h
  include/quda.h
  include/quda_milc_interface.h
  lib/check_params.h
  lib/comm_common.cpp
  lib/dirac_clover.cpp
  lib/dirac_clover_hasenbusch_twist.cpp
  lib/dirac_improved_staggered.cpp
  lib/dirac_twisted_clover.cpp
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/multigrid.cpp
  tests/multigrid_evolve_test.cpp
  utils/command_line_params.cpp
  utils/command_line_params.h
  utils/set_params.cpp
Labels: feature

#1034 Feature/device
  include/device.h
  include/malloc_quda.h
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/dslash_policy.cuh
  lib/dslash_quda.cu
  lib/gauge_observable.cpp
  lib/interface_quda.cpp
  lib/lattice_field.cpp
  lib/reduce_quda.cu
  lib/targets/cuda/CMakeLists.txt
  lib/targets/cuda/device.cpp
  lib/targets/cuda/malloc.cpp
  tests/unitarize_link_test.cpp
Labels: clean-up

#1035 Feature/milc multishift double
  lib/milc_interface.cpp
Labels: bug, feature

#1025 Feature/clang2
  CMakeLists.txt
  doc/CMakeLists.txt
  include/color_spinor_field_order.h
  include/gauge_field_order.h
  include/kernels/block_orthogonalize.cuh
  include/quda_matrix.h
  include/thrust_helper.cuh
  include/util_quda.h
  include/vector_io.h
  lib/CMakeLists.txt
  lib/targets/cuda/CMakeLists.txt
  lib/vector_io.cpp
  tests/CMakeLists.txt
  tests/multigrid_benchmark_test.cpp
Labels: build
