Repository lattice/quda, pull requests merged in 2020-11, with the labels that each got.

#1067 Staggered aggregation coarsening and optimized Kahler-Dirac operator
  include/color_spinor_field.h
  include/dirac_quda.h
  include/dslash_quda.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/gauge_field_order.h
  include/index_helper.cuh
  include/invert_quda.h
  include/kernels/block_orthogonalize.cuh
  include/kernels/coarse_op_kernel.cuh
  include/kernels/restrictor.cuh
  include/kernels/staggered_kd_apply_xinv_kernel.cuh
  include/kernels/staggered_kd_build_xinv_kernel.cuh
  include/matrix_tile.cuh
  include/multigrid.h
  include/quda.h
  include/staggered_kd_build_xinv.h
  include/transfer.h
  lib/CMakeLists.txt
  lib/block_orthogonalize.cu
  lib/check_params.h
  lib/coarse_op.cu
  lib/coarse_op.cuh
  lib/coarse_op_mma_launch.h
  lib/coarsecoarse_op.cu
  lib/color_spinor_field.cpp
  lib/color_spinor_pack.cu
  lib/copy_color_spinor_mg.cuh
  lib/cpu_gauge_field.cpp
  lib/cuda_gauge_field.cpp
  lib/dirac.cpp
  lib/dirac_clover.cpp
  lib/dirac_coarse.cpp
  lib/dirac_improved_staggered.cpp
  lib/dirac_improved_staggered_kd.cpp
  lib/dirac_staggered.cpp
  lib/dirac_staggered_kd.cpp
  lib/dirac_twisted_clover.cpp
  lib/dirac_twisted_mass.cpp
  lib/dirac_wilson.cpp
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/multigrid.cpp
  lib/prolongator.cu
  lib/restrictor.cu
  lib/staggered_coarse_op.cu
  lib/staggered_kd_apply_xinv.cu
  lib/staggered_kd_build_xinv.cu
  lib/transfer.cpp
  tests/staggered_invert_test.cpp
  utils/command_line_params.cpp
  utils/command_line_params.h
  utils/set_params.cpp
  utils/staggered_host_utils.cpp
Labels: bug, feature, optimization

#1077 Move singularity of recon-8 to {{0,1,0},{1,0,0},{0,0,-1}}
  host_reference/dslash_reference.cpp
  include/gauge_field_order.h
  lib/solver.cpp
Labels: clean-up, feature

#1022 Feature/cublas interface
  README.md
  host_reference/CMakeLists.txt
  host_reference/blas_reference.cpp
  host_reference/blas_reference.h
  include/blas_lapack.h
  include/clover_field_order.h
  include/device.h
  include/eigensolve_quda.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/gauge_field_order.h
  include/instantiate.h
  include/kernels/laplace.cuh
  include/quda.h
  include/quda_api.h
  include/quda_internal.h
  include/reduce_helper.h
  include/transform_reduce.h
  include/tune_quda.h
  lib/CMakeLists.txt
  lib/check_params.h
  lib/comm_common.cpp
  lib/cuda_gauge_field.cpp
  lib/eig_iram.cpp
  lib/eigensolve_quda.cpp
  lib/interface/CMakeLists.txt
  lib/interface/blas_interface.cpp
  lib/interface_quda.cpp
  lib/inv_eigcg_quda.cpp
  lib/milc_interface.cpp
  lib/targets/cuda/blas_lapack_cublas.cpp
  lib/targets/cuda/device.cpp
  lib/targets/generic/blas_lapack_eigen.cpp
  lib/targets/hip/device.cpp
  lib/targets/hip/malloc.cpp
  tests/CMakeLists.txt
  tests/blas_interface_test.cpp
  tests/contract_test.cpp
  tests/gauge_force_test.cpp
  utils/command_line_params.cpp
  utils/command_line_params.h
Labels: feature

#1076 Template cleanup of coarsening routines
  include/kernels/coarse_op_kernel.cuh
  lib/coarse_op.cuh
Labels: clean-up

#1078 Rework handling of targets in cmake
  CMakeLists.txt
  host_reference/CMakeLists.txt
  lib/CMakeLists.txt
  lib/interface/CMakeLists.txt
  lib/targets/cuda/CMakeLists.txt
  lib/targets/generic/CMakeLists.txt
  lib/targets/hip/CMakeLists.txt
  tests/CMakeLists.txt
  tests/host_reference/CMakeLists.txt
  tests/host_reference/README.md
  tests/host_reference/blas_reference.cpp
  tests/host_reference/blas_reference.h
  tests/host_reference/clover_reference.cpp
  tests/host_reference/contract_reference.h
  tests/host_reference/covdev_reference.cpp
  tests/host_reference/covdev_reference.h
  tests/host_reference/domain_wall_dslash_reference.cpp
  tests/host_reference/domain_wall_dslash_reference.h
  tests/host_reference/dslash_reference.cpp
  tests/host_reference/dslash_reference.h
  tests/host_reference/dslash_test_helpers.cpp
  tests/host_reference/dslash_test_helpers.h
  tests/host_reference/gauge_force_reference.cpp
  tests/host_reference/gauge_force_reference.h
  tests/host_reference/hisq_force_reference.cpp
  tests/host_reference/hisq_force_reference.h
  tests/host_reference/hisq_force_reference2.cpp
  tests/host_reference/staggered_dslash_reference.cpp
  tests/host_reference/staggered_dslash_reference.h
  tests/host_reference/wilson_dslash_reference.cpp
  tests/host_reference/wilson_dslash_reference.h
  tests/utils/CMakeLists.txt
  tests/utils/README.md
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
  tests/utils/face_gauge.cpp
  tests/utils/host_blas.cpp
  tests/utils/host_utils.cpp
  tests/utils/host_utils.h
  tests/utils/llfat_utils.cpp
  tests/utils/llfat_utils.h
  tests/utils/misc.cpp
  tests/utils/misc.h
  tests/utils/set_params.cpp
  tests/utils/short.h
  tests/utils/staggered_gauge_utils.cpp
  tests/utils/staggered_gauge_utils.h
  tests/utils/staggered_host_utils.cpp
  utils/CMakeLists.txt
Labels: build, clean-up
