Repository lattice/quda, pull requests merged in 2020-08, with the labels that each got.

#1039 Feature/atomic reduce
  CMakeLists.txt
  host_reference/domain_wall_dslash_reference.cpp
  include/blas_helper.cuh
  include/blas_quda.h
  include/cub_helper.cuh
  include/externals/jitify.hpp
  include/float_vector.h
  include/kernels/blas_core.cuh
  include/kernels/clover_invert.cuh
  include/kernels/dslash_coarse.cuh
  include/kernels/gauge_plaq.cuh
  include/kernels/gauge_qcharge.cuh
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/kernels/reduce_core.cuh
  include/launch_kernel.cuh
  include/mdw_dslash5_tensor_core.cuh
  include/mma_tensor_op/mma_m16n16k16_sm70.cuh
  include/multi_blas_helper.cuh
  include/quda_define.h.in
  include/reduce_helper.h
  include/register_traits.h
  include/transform_reduce.h
  lib/CMakeLists.txt
  lib/blas_quda.cu
  lib/checksum.cu
  lib/clover_invert.cu
  lib/dslash_coarse.hpp
  lib/gauge_fix_fft.cu
  lib/gauge_fix_ovr.cu
  lib/gauge_plaq.cu
  lib/gauge_qcharge.cu
  lib/gauge_random.cu
  lib/interface_quda.cpp
  lib/mdw_fused_dslash.cu
  lib/momentum.cu
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/pgauge_det_trace.cu
  lib/pgauge_exchange.cu
  lib/pgauge_heatbath.cu
  lib/pgauge_init.cu
  lib/quda_cuda_api.cpp
  lib/reduce_helper.cu
  lib/reduce_quda.cu
  lib/targets/cuda/tune.cpp
  tests/blas_test.cpp
  tests/plaq_test.cpp
  utils/host_utils.cpp
Labels: bug, clean-up, feature, optimization

#1049 switch eigen download url to gitlab
  CMakeLists.txt
Labels: build

#1006 Add Tensor Core MMA Support to Multigrid
  include/color_spinor_field.h
  include/color_spinor_field_order.h
  include/dirac_quda.h
  include/dslash.h
  include/externals/trove/aos.h
  include/externals/trove/transpose.h
  include/float_vector.h
  include/gauge_field_order.h
  include/kernels/coarse_op_kernel.cuh
  include/kernels/coarse_op_kernel_mma.cuh
  include/kernels/coarse_op_preconditioned.cuh
  include/kernels/coarse_op_preconditioned_mma.cuh
  include/lattice_field.h
  include/mdw_dslash5_tensor_core.cuh
  include/mma_tensor_op/gemm.cuh
  include/mma_tensor_op/hmma_m16n16k16_sm70.cuh
  include/mma_tensor_op/hmma_m16n8k8_sm80.cuh
  include/mma_tensor_op/mma_m16n16k16_sm70.cuh
  include/multigrid.h
  include/quda.h
  include/register_traits.h
  lib/check_params.h
  lib/coarse_op.cuh
  lib/coarse_op_mma_launch.h
  lib/coarse_op_preconditioned.cu
  lib/coarse_op_preconditioned_mma_launch.h
  lib/coarsecoarse_op.cu
  lib/color_spinor_field.cpp
  lib/color_spinor_pack.cu
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/dirac_coarse.cpp
  lib/dslash_pack2.cu
  lib/extract_gauge_ghost_mg.cu
  lib/gauge_field.cpp
  lib/lattice_field.cpp
  lib/mdw_fused_dslash.cu
  lib/milc_interface.cpp
  lib/multigrid.cpp
  utils/command_line_params.cpp
  utils/command_line_params.h
  utils/set_params.cpp
Labels: feature, optimization
