Repository lattice/quda, pull requests merged in 2020-05, with the labels that each got.

#980 add optional ability to install QUDA tests
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#990 Feature/dwf io
  CMakeLists.txt
  include/color_spinor_field.h
  include/eigensolve_quda.h
  include/layout_hyper.h
  include/qio_field.h
  include/qio_util.h
  include/quda.h
  include/vector_io.h
  lib/CMakeLists.txt
  lib/check_params.h
  lib/color_spinor_field.cpp
  lib/eigensolve_quda.cpp
  lib/layout_hyper.c
  lib/layout_hyper.cpp
  lib/milc_interface.cpp
  lib/multigrid.cpp
  lib/qio_field.cpp
  lib/qio_util.cpp
  lib/vector_io.cpp
  utils/command_line_params.cpp
  utils/command_line_params.h
  utils/set_params.cpp
Labels: bug, clean-up, feature

#984 Feature/block trlm
  include/clover_field_order.h
  include/color_spinor_field_order.h
  include/eigensolve_quda.h
  include/enum_quda.h
  include/gauge_field_order.h
  include/quda.h
  lib/CMakeLists.txt
  lib/check_params.h
  lib/eig_block_trlm.cpp
  lib/eig_trlm.cpp
  lib/eigensolve_quda.cpp
  tests/eigensolve_test.cpp
  utils/command_line_params.cpp
  utils/command_line_params.h
  utils/set_params.cpp
Labels: feature

#992 Fix staggered_invert_test with naive staggered fermions
  tests/staggered_invert_test.cpp
Labels: bug

#993 Feature/ampere
  CMakeLists.txt
  include/thrust_helper.cuh
  include/tune_quda.h
Labels: clean-up, feature

#995 CMake cleanup
  CMakeLists.txt
  cmake/FindCUDALibs.cmake
  cmake/FindCUDAWrapper.cmake
  host_reference/CMakeLists.txt
  lib/CMakeLists.txt
  lib/dslash5_domain_wall.cu
  lib/unitarize_force_quda.cu
  lib/unitarize_links_quda.cu
  tests/CMakeLists.txt
  utils/CMakeLists.txt
Labels: build
