Repository lattice/quda, pull requests merged in 2021-02, with the labels that each got.

#1106 Fix compilations with QDPJIT and BQCD order and small fixes
  CMakeLists.txt
  lib/CMakeLists.txt
  lib/copy_clover_offset.cu
  lib/milc_interface.cpp
  tests/dslash_test.cpp
Labels: bug, clean-up

#1107 Fixes for QMP communicators
  include/communicator_quda.h
  lib/communicator_qmp.cpp
  lib/util_quda.cpp
Labels: bug

#1109 Add support for optionally running some benchmarks from ctest
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: build, feature

#1110 Fix performance of heterogeneous atomic reductions
  include/reduce_helper.h
Labels: optimization

#1112 Remove variable-size arrays from dslash test code
  tests/blas_interface_test.cpp
  tests/blas_test.cpp
  tests/contract_test.cpp
  tests/covdev_test.cpp
  tests/deflated_invert_test.cpp
  tests/dslash_test_utils.h
  tests/eigensolve_test.cpp
  tests/heatbath_test.cpp
  tests/host_reference/covdev_reference.cpp
  tests/host_reference/domain_wall_dslash_reference.cpp
  tests/host_reference/dslash_reference.cpp
  tests/host_reference/dslash_reference.h
  tests/host_reference/staggered_dslash_reference.cpp
  tests/host_reference/wilson_dslash_reference.cpp
  tests/invert_test.cpp
  tests/invertmsrc_test.cpp
  tests/multigrid_evolve_test.cpp
  tests/staggered_dslash_test_utils.h
  tests/staggered_eigensolve_test.cpp
  tests/staggered_invert_test.cpp
  tests/staggered_invertmsrc_test.cpp
  tests/utils/host_utils.cpp
  tests/utils/host_utils.h
Labels: bug
