Repository lattice/quda, pull requests merged in 2021-04, with the labels that each got.

#1138 MILC HISQ MG struct initialization hotfix
  lib/milc_interface.cpp
Labels: bug

#1140 potential size reuction for libquda
  lib/targets/cuda/CMakeLists.txt
Labels: build

#1142 Hotfix/shmem cleanup
  include/dslash_helper.cuh
  include/kernels/dslash_domain_wall_5d.cuh
  include/kernels/dslash_pack.cuh
Labels: clean-up

#1141 Hotfix/misc 1.1
  include/multigrid.h
  include/shmem_helper.cuh
  include/tune_quda.h
  lib/CMakeLists.txt
  lib/coarse_op_preconditioned.cu
  lib/color_spinor_pack.cu
  lib/dslash_coarse.hpp
  lib/targets/cuda/CMakeLists.txt
  lib/targets/cuda/tune.cpp
  lib/targets/hip/CMakeLists.txt
  lib/tune.cpp
Labels: bug
