Repository lattice/quda, pull requests merged in 2021-01, with the labels that each got.

#1093 Hotfix/milc qio support
  CMakeLists.txt
  include/layout_hyper.h
  lib/layout_hyper.cpp
  lib/qio_field.cpp
Labels: bug, feature

#1100 Fix a potential race condition in multi-GPU heatbath evolution
  lib/pgauge_exchange.cu
Labels: bug

#1020 Allow QUDA to have multiple communicators and Split Grid
  README.md
  include/clover_field.h
  include/color_spinor_field.h
  include/comm_key.h
  include/comm_quda.h
  include/communicator_quda.h
  include/dirac_quda.h
  include/gauge_field.h
  include/gauge_field_order.h
  include/kernels/copy_field_offset.cuh
  include/lattice_field.h
  include/quda.h
  include/split_grid.h
  include/util_quda.h
  lib/CMakeLists.txt
  lib/check_params.h
  lib/clover_field.cpp
  lib/comm_common.cpp
  lib/comm_mpi.cpp
  lib/comm_qmp.cpp
  lib/comm_single.cpp
  lib/communicator_mpi.cpp
  lib/communicator_qmp.cpp
  lib/communicator_single.cpp
  lib/communicator_stack.cpp
  lib/copy_clover_offset.cu
  lib/copy_color_spinor_offset.cu
  lib/copy_gauge_offset.cu
  lib/cpu_color_spinor_field.cpp
  lib/cpu_gauge_field.cpp
  lib/cuda_color_spinor_field.cpp
  lib/cuda_gauge_field.cpp
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/solver.cpp
  lib/targets/cuda/tune.cpp
  lib/timer.cpp
  tests/dslash_ctest.cpp
  tests/dslash_test.cpp
  tests/dslash_test_utils.h
  tests/host_reference/dslash_reference.cpp
  tests/invert_test.cpp
  tests/staggered_dslash_ctest.cpp
  tests/staggered_dslash_test.cpp
  tests/staggered_dslash_test_utils.h
  tests/staggered_invert_test.cpp
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
  tests/utils/host_utils.cpp
  tests/utils/host_utils.h
Labels: feature

#1102 Hotfix/misc
  include/quda.h
  lib/random.cu
  lib/targets/cuda/quda_api.cpp
Labels: bug
