Repository lattice/quda, pull requests merged in 2021-05, with the labels that each got.

#1144 Move über kernel into a separate kernel instantiation
  CMakeLists.txt
  include/complex_quda.h
  include/dslash.h
  include/dslash_helper.cuh
  include/index_helper.cuh
  include/kernels/dslash_ndeg_twisted_mass_preconditioned.cuh
  lib/covDev.cu
  lib/dslash_domain_wall_5d.cu
  lib/dslash_improved_staggered.cu
  lib/dslash_ndeg_twisted_mass.cu
  lib/dslash_ndeg_twisted_mass_preconditioned.cu
  lib/dslash_policy.cuh
  lib/dslash_twisted_clover.cu
  lib/dslash_twisted_clover_preconditioned.cu
  lib/dslash_twisted_mass.cu
  lib/dslash_twisted_mass_preconditioned.cu
  lib/dslash_wilson_clover.cu
  lib/dslash_wilson_clover_hasenbusch_twist.cu
  lib/dslash_wilson_clover_hasenbusch_twist_preconditioned.cu
  lib/dslash_wilson_clover_preconditioned.cu
  lib/laplace.cu
  lib/lattice_field.cpp
  tests/dslash_ctest.cpp
  tests/dslash_test_utils.h
  tests/staggered_dslash_ctest.cpp
  tests/staggered_dslash_test.cpp
  tests/staggered_dslash_test_utils.h
Labels: optimization

#1148 Hotfix/dslash ndimcomms
  include/complex_quda.h
  include/dslash.h
  lib/color_spinor_util.cu
  tests/CMakeLists.txt
  tests/blas_test.cpp
Labels: bug

#1152 (Temporarily) remove multisrc tests
  tests/CMakeLists.txt
  tests/invertmsrc_test.cpp
  tests/staggered_invertmsrc_test.cpp
Labels: bug, clean-up

#1154 Hotfix/mg single fixes
  README.md
  lib/block_orthogonalize.cu
  lib/coarse_op.cu
  lib/coarsecoarse_op.cu
  lib/communicator_single.cpp
  lib/dslash_coarse.hpp
  tests/dslash_test.cpp
  tests/staggered_dslash_test.cpp
  tests/utils/host_utils.cpp
Labels: bug
