Repository lattice/quda, pull requests merged in 2022-09, with the labels that each got.

#1308 Gauge observables: trace of arbitrary gauge loops (useful for gauge action), Polyakov loop
  include/gauge_force_quda.h
  include/gauge_path_helper.cuh
  include/gauge_path_quda.h
  include/gauge_tools.h
  include/kernels/gauge_force.cuh
  include/kernels/gauge_loop_trace.cuh
  include/kernels/gauge_polyakov_loop.cuh
  include/quda.h
  include/quda_milc_interface.h
  include/targets/cuda/thread_array.h
  include/targets/hip/thread_array.h
  include/tunable_reduction.h
  lib/CMakeLists.txt
  lib/check_params.h
  lib/gauge_force.cu
  lib/gauge_loop_trace.cu
  lib/gauge_observable.cpp
  lib/gauge_phase.cu
  lib/gauge_polyakov_loop.cu
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  tests/CMakeLists.txt
  tests/gauge_alg_test.cpp
  tests/gauge_path_test.cpp
  tests/host_reference/gauge_force_reference.cpp
  tests/host_reference/gauge_force_reference.h
  tests/sanity_check.sh
  tests/su3_test.cpp
Labels: feature, clean-up, optimization

#1298 Feature/milc gaugefix ovr definition
  include/quda.h
  include/quda_milc_interface.h
  lib/gauge_fix_ovr.cu
  lib/interface_quda.cpp
  lib/milc_interface.cpp
Labels: feature, clean-up

#1324 Hotfix for weird heavy quark residual behavior during MG setup
  lib/inv_cg_quda.cpp
Labels: bug, clean-up
