Repository lattice/quda, pull requests merged in 2022-01, with the labels that each got.

#1230 Feature/multi blas misc
  include/blas_quda.h
  include/kernels/multi_blas_core.cuh
  include/kernels/multi_reduce_core.cuh
  include/kernels/reduce_init.cuh
  include/kernels/transform_reduce.cuh
  include/multi_blas_helper.cuh
  include/quda_constants.h
  include/reducer.h
  include/targets/cuda/reduce_helper.h
  include/targets/cuda/reduction_kernel.h
  include/targets/generic/reduce_helper.h
  include/tunable_reduction.h
  include/tune_quda.h
  lib/blas_quda.cu
  lib/interface_quda.cpp
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/reduce_helper.cu
  lib/transform_reduce.cu
  tests/blas_test.cpp
Labels: bug, feature

#1232 Fix bug where reduceEnd was being destroyed when not created
  lib/reduce_helper.cu
Labels: bug

#1233 Fix UB in host multi-reduction kernel
  include/targets/generic/reduction_kernel_host.h
Labels: bug

#1221 Optimized Kahler-Dirac operator for staggered/HISQ MG
  include/color_spinor_field.h
  include/color_spinor_field_order.h
  include/dirac_quda.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/kernels/coarse_op_kernel.cuh
  include/kernels/coarse_op_kernel_mma.cuh
  include/kernels/staggered_coarse_op_kernel.cuh
  include/kernels/staggered_kd_apply_xinv_kernel.cuh
  include/kernels/staggered_kd_reorder_xinv_kernel.cuh
  include/multigrid.h
  include/quda.h
  include/staggered_kd_build_xinv.h
  lib/CMakeLists.txt
  lib/block_orthogonalize.cu
  lib/check_params.h
  lib/coarse_op.cu
  lib/coarse_op.cuh
  lib/coarse_op_mma_launch.h
  lib/coarsecoarse_op.hpp
  lib/color_spinor_field.cpp
  lib/color_spinor_pack.cu
  lib/cpu_gauge_field.cpp
  lib/dirac_clover.cpp
  lib/dirac_clover_hasenbusch_twist.cpp
  lib/dirac_coarse.cpp
  lib/dirac_improved_staggered.cpp
  lib/dirac_improved_staggered_kd.cpp
  lib/dirac_staggered.cpp
  lib/dirac_staggered_kd.cpp
  lib/dirac_twisted_clover.cpp
  lib/dirac_twisted_mass.cpp
  lib/dirac_wilson.cpp
  lib/dslash_staggered.cu
  lib/gauge_field.cpp
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  lib/multigrid.cpp
  lib/staggered_coarse_op.cu
  lib/staggered_kd_apply_xinv.cu
  lib/staggered_kd_build_xinv.cu
  lib/staggered_kd_reorder_xinv.cu
  lib/transfer.cpp
  tests/heatbath_test.cpp
  tests/multigrid_evolve_test.cpp
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
  tests/utils/set_params.cpp
Labels: feature, clean-up, optimization

#1235 Improvements to fixed-iteration CA-CG
  include/blas_quda.h
  include/invert_quda.h
  include/kernels/blas_core.cuh
  include/kernels/multi_blas_core.cuh
  include/quda.h
  lib/blas_quda.cu
  lib/check_params.h
  lib/eigensolve_quda.cpp
  lib/interface_quda.cpp
  lib/inv_ca_cg.cpp
  lib/inv_ca_gcr.cpp
  lib/inv_pcg_quda.cpp
  lib/multi_blas_quda.cu
  lib/quda_fortran.F90
  tests/blas_test.cpp
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
  tests/utils/set_params.cpp
Labels: feature, clean-up, optimization

#1206 Separate target specific cmake options into target specific CMakeLists
  CMakeLists.txt
  QUDAConfig.cmake.in
  include/blas_magma.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/quda.h
  include/quda_define.h.in
  lib/CMakeLists.txt
  lib/blas_magma.cu
  lib/blas_magma_nopiv.cu
  lib/deflation.cpp
  lib/interface_quda.cpp
  lib/inv_eigcg_quda.cpp
  lib/inv_gmresdr_quda.cpp
  lib/quda_fortran.F90
  lib/targets/cuda/CMakeLists.txt
  lib/targets/cuda/target_cuda.cmake
  tests/CMakeLists.txt
  tests/utils/command_line_params.cpp
Labels: build

#1061 Add dynamically trained MADWF blocking to MSPCG
  include/accelerator.h
  include/device_vector.h
  include/dirac_quda.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/invert_preconditioner.h
  include/invert_quda.h
  include/invert_x_update.h
  include/kernels/device_vector_axpby.cuh
  include/kernels/madwf_tensor.cuh
  include/kernels/madwf_transfer.cuh
  include/madwf_ml.h
  include/madwf_param.h
  include/polynomial.h
  include/quda.h
  include/reliable_updates.h
  include/targets/cuda/reduce_helper.h
  include/targets/generic/reduce_helper.h
  include/timer.h
  lib/CMakeLists.txt
  lib/check_params.h
  lib/device_vector.cu
  lib/dirac_domain_wall.cpp
  lib/dirac_mobius.cpp
  lib/interface_quda.cpp
  lib/inv_ca_cg.cpp
  lib/inv_cg_quda.cpp
  lib/inv_pcg_quda.cpp
  lib/madwf_ml.cpp
  lib/madwf_tensor.cu
  lib/madwf_transfer.cu
  lib/madwf_transfer.h
  lib/quda_fortran.F90
  lib/timer.cpp
  tests/invert_test.cpp
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
  tests/utils/host_utils.cpp
  tests/utils/host_utils.h
  tests/utils/set_params.cpp
Labels: feature
