Repository lattice/quda, pull requests merged in 2022-04, with the labels that each got.

#1259 Hotfix/overflow test fixes
  lib/dslash_policy.cuh
  tests/contract_test.cpp
  tests/deflated_invert_test.cpp
  tests/host_reference/covdev_reference.cpp
  tests/host_reference/domain_wall_dslash_reference.cpp
  tests/host_reference/staggered_dslash_reference.cpp
  tests/host_reference/wilson_dslash_reference.cpp
  tests/unitarize_link_test.cpp
  tests/utils/host_utils.cpp
  tests/utils/host_utils.h
  tests/utils/staggered_host_utils.cpp
Labels: bug

#1260 prototype for a 2-step tuning process.
  LICENSE
  include/dslash.h
  include/externals/.clang-format
  include/externals/json.hpp
  include/json_helper.h
  include/tune_quda.h
  lib/blas_quda.cu
  lib/coarse_op.cuh
  lib/dslash_coarse.hpp
  lib/dslash_pack2.cu
  lib/dslash_policy.cuh
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/reduce_quda.cu
  lib/restrictor.cu
  lib/tune.cpp
Labels: optimization

#1264 Mixed precision staggered KD setup
  include/dirac_quda.h
  include/multigrid.h
  include/staggered_kd_build_xinv.h
  lib/interface_quda.cpp
  lib/multigrid.cpp
  lib/staggered_kd_build_xinv.cu
Labels: clean-up, optimization
