Repository lattice/quda, pull requests merged in 2022-05, with the labels that each got.

#1267 Feature/dilution
  include/color_spinor_field.h
  include/enum_quda.h
  include/enum_quda_fortran.h
  include/instantiate.h
  include/kernels/spinor_dilute.cuh
  include/targets/cuda/math_helper.cuh
  lib/CMakeLists.txt
  lib/spinor_dilute.cu
  lib/spinor_noise.cu
  tests/CMakeLists.txt
  tests/dilution_test.cpp
  tests/utils/misc.cpp
  tests/utils/misc.h
Labels: bug, feature

#1268 Added manual specification of gauge field locations to heatbath_test, some gauge algorithms
  lib/gauge_observable.cpp
  lib/interface_quda.cpp
  tests/heatbath_test.cpp
Labels: bug

#1272 Staggered MG hotfix: field location and zeroing for coarse KD build.
  lib/staggered_coarse_op.cu
  lib/staggered_kd_build_xinv.cu
Labels: bug

#1228 Feature/shmem exchangeghost
  include/color_spinor_field.h
  include/dslash.h
  include/dslash_helper.cuh
  include/dslash_quda.h
  include/kernels/color_spinor_pack.cuh
  include/kernels/dslash_pack.cuh
  include/kernels/dslash_shmem_helper.cuh
  include/shmem_pack_helper.cuh
  lib/CMakeLists.txt
  lib/color_spinor_field.cpp
  lib/color_spinor_pack.cu
  lib/dslash_coarse.hpp
  lib/dslash_policy.cuh
  lib/dslash_quda.cu
  lib/targets/cuda/comm_target.cpp
  lib/targets/cuda/target_cuda.cmake
  lib/targets/hip/comm_target.cpp
Labels: optimization

#1282 Hotfix/nvshmem 11.5
  include/dslash_helper.cuh
  include/dslash_quda.h
  include/dslash_shmem.h
  include/kernels/color_spinor_pack.cuh
  include/kernels/dslash_shmem_helper.cuh
  lib/color_spinor_pack.cu
  lib/dslash_coarse.hpp
  lib/dslash_policy.cuh
  lib/dslash_quda.cu
Labels: bug
