Repository lattice/quda, pull requests merged in 2022-06, with the labels that each got.

#1285 Feature/sincospi
  CMakeLists.txt
  include/gauge_field_order.h
  include/instantiate.h
  include/kernels/clover_deriv.cuh
  include/kernels/field_strength_tensor.cuh
  include/kernels/gauge_fix_fft.cuh
  include/kernels/gauge_fix_ovr.cuh
  include/kernels/gauge_heatbath.cuh
  include/kernels/gauge_random.cuh
  include/kernels/gauge_stout.cuh
  include/kernels/gauge_utils.cuh
  include/kernels/gauge_wilson_flow.cuh
  include/kernels/spinor_noise.cuh
  include/multigrid.h
  include/quda_matrix.h
  include/targets/cuda/FFT_Plans.h
  include/targets/cuda/math_helper.cuh
  include/targets/hip/FFT_Plans.h
  include/targets/hip/math_helper.cuh
  lib/CMakeLists.txt
  lib/extract_gauge_ghost_mg.cu
  lib/gauge_ape.cu
  lib/gauge_field_strength_tensor.cu
  lib/gauge_fix_fft.cu
  lib/gauge_fix_ovr.cu
  lib/gauge_force.cu
  lib/gauge_phase.cu
  lib/gauge_plaq.cu
  lib/gauge_qcharge.cu
  lib/gauge_stout.cu
  lib/gauge_update_quda.cu
  lib/gauge_wilson_flow.cu
  lib/hisq_paths_force_quda.cu
  lib/llfat_quda.cu
  lib/milc_interface.cpp
  lib/momentum.cu
  lib/pgauge_det_trace.cu
  lib/pgauge_exchange.cu
  lib/pgauge_heatbath.cu
  lib/pgauge_init.cu
  lib/prolongator.cu
  lib/restrictor.cu
  lib/targets/cuda/target_cuda.cmake
  lib/targets/hip/target_hip.cmake
  lib/unitarize_force_quda.cu
  lib/unitarize_links_quda.cu
  tests/CMakeLists.txt
  tests/su3_test.cpp
Labels: feature, clean-up, optimization, build

#1288 Hotfix/hdot
  include/blas_quda.h
  include/kernels/multi_blas_core.cuh
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  tests/blas_test.cpp
  tests/multigrid_evolve_test.cpp
Labels: bug, clean-up

#1290 Made the include of json.hpp come from include/external
  include/json_helper.h
Labels: bug

#1292 Hotfix/vuv
  lib/coarse_op.cuh
  lib/tune.cpp
Labels: bug, optimization
