Repository lattice/quda, pull requests merged in 2023-01, with the labels that each got.

#1347 Hotfix/dslashcoarsesync
  include/kernels/coarse_op_kernel_mma.cuh
  include/kernels/color_spinor_pack.cuh
  include/targets/cuda/shared_memory_cache_helper.h
  include/targets/cuda/target_device.h
  include/targets/cuda/thread_array.h
  include/targets/hip/shared_memory_cache_helper.h
  include/targets/hip/target_device.h
  include/targets/hip/thread_array.h
  lib/color_spinor_field.cpp
  lib/color_spinor_pack.cu
Labels: bug

#1351 Remove MILC gauge order from HISQ force verification code
  tests/hisq_paths_force_test.cpp
  tests/host_reference/hisq_force_reference.cpp
  tests/host_reference/hisq_force_reference.h
Labels: clean-up

#1349 Few minor changes
  CMakeLists.txt
  QUDAConfig.cmake.in
  lib/copy_gauge_inc.cu
Labels: lyncs

#1352 Hotfix/libquda test shared
  lib/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build
