Repository lattice/quda, pull requests merged in 2023-03, with the labels that each got.

#1362 QUDA interface `freeGaugeQuda` clean-up
  include/quda.h
  lib/interface_quda.cpp
Labels: bug, feature, clean-up

#1364 Feature/large kernel args
  include/dslash.h
  include/kernels/multi_blas_core.cuh
  include/multi_blas_helper.cuh
  include/quda_define.h.in
  include/targets/cuda/constant_kernel_arg.h
  include/targets/cuda/target_device.h
  include/targets/cuda/tunable_kernel.h
  include/targets/hip/constant_kernel_arg.h
  include/targets/hip/tunable_kernel.h
  include/tunable_block_reduction.h
  include/tunable_nd.h
  include/tunable_reduction.h
  include/tune_quda.h
  lib/blas_quda.cu
  lib/copy_gauge_helper.hpp
  lib/covDev.cu
  lib/dslash_coarse.hpp
  lib/dslash_domain_wall_4d_fused_m5.hpp
  lib/dslash_policy.cuh
  lib/laplace.cu
  lib/multi_blas_quda.cu
  lib/multi_reduce_quda.cu
  lib/pgauge_exchange.cu
  lib/reduce_quda.cu
  lib/staggered_quark_smearing.cu
  lib/targets/cuda/quda_api.cpp
  lib/targets/cuda/target_cuda.cmake
  lib/targets/hip/quda_api.cpp
  lib/util_quda.cpp
Labels: feature, optimization

#1367 Fat/long force optimizations
  include/gauge_field_order.h
  include/instantiate.h
  include/kernels/hisq_paths_force.cuh
  include/quda_matrix.h
  include/unitarization_links.h
  lib/hisq_paths_force_quda.cu
  lib/interface_quda.cpp
  lib/milc_interface.cpp
  tests/hisq_paths_force_test.cpp
  tests/host_reference/hisq_force_reference.cpp
  tests/host_reference/hisq_force_reference.h
  tests/utils/host_utils.cpp
  tests/utils/host_utils.h
Labels: clean-up, optimization
