Repository lattice/quda, pull requests merged in 2023-08, with the labels that each got.

#1390 Preconditioner cleanup
  include/accelerator.h
  include/invert_preconditioner.h
  include/invert_quda.h
  include/multigrid.h
  lib/inv_bicgstab_quda.cpp
  lib/inv_gcr_quda.cpp
  lib/inv_pcg_quda.cpp
  lib/solver.cpp
  tests/eigensolve_test_gtest.hpp
  tests/utils/set_params.cpp
Labels: feature, clean-up

#1398 `PARTFILE` support for near-null vectors (and eigenvectors)
  include/multigrid.h
  include/qio_field.h
  include/quda.h
  include/vector_io.h
  lib/check_params.h
  lib/eigensolve_quda.cpp
  lib/milc_interface.cpp
  lib/multigrid.cpp
  lib/qio_field.cpp
  lib/vector_io.cpp
  tests/io_test.cpp
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
  tests/utils/set_params.cpp
Labels: feature, optimization

#1395 add github actions build for CUDA
  .github/workflows/cuda_githubactions_build.yml
  CMakeLists.txt
  cmake/CPM.cmake
  lib/coarse_op.cuh
  lib/dslash_coarse.hpp
  lib/targets/cuda/target_cuda.cmake
Labels: build

#1401 Specifying granular masses and tolerances for multishift tests
  tests/invert_test.cpp
  tests/staggered_invert_test.cpp
  tests/utils/command_line_params.cpp
  tests/utils/command_line_params.h
Labels: feature, clean-up
